apiVersion: v1
kind: Service
metadata:
  name: codecrafters-service
  namespace: kubernetes-dashboard
spec:
  type: LoadBalancer
  selector:
    app: serving-web-content-codecrafters
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000