# Generated by Django 3.2.9 on 2024-06-18 13:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('group', '0003_auto_20240618_2140'),
    ]

    operations = [
        migrations.CreateModel(
            name='pl_graph_api',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('embed_link', models.CharField(max_length=255)),
                ('chart_type', models.CharField(max_length=255)),
                ('Person_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='pl_graph_sharing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, null=True)),
                ('description', models.CharField(max_length=255, null=True)),
                ('link', models.CharField(max_length=255)),
                ('chart_type', models.CharField(max_length=255)),
                ('Group_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='group.group_tbl')),
                ('Person_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='pl_table_sharing',
        ),
    ]
