# Generated by Django 3.2.9 on 2024-06-19 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0005_auto_20240619_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pl_graph_sharing',
            name='chart_type',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
