# Generated by Django 3.2.9 on 2024-06-13 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0003_basket_prodreview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prodreview',
            name='basketid',
        ),
        migrations.RemoveField(
            model_name='prodreview',
            name='productid',
        ),
        migrations.DeleteModel(
            name='prodReview',
        ),
    ]
