# Generated by Django 3.2.9 on 2024-06-25 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0006_remove_prodproduct_test_fix'),
    ]

    operations = [
        migrations.AddField(
            model_name='prodproduct',
            name='productSold',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='prodproduct',
            name='productPrice',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
