# Generated by Django 3.2.9 on 2024-06-26 03:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0007_auto_20240625_2314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prodproduct',
            name='productStock',
        ),
        migrations.CreateModel(
            name='prodStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.IntegerField(default=0)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='marketplace.prodproduct')),
            ],
            options={
                'db_table': 'prodStock',
            },
        ),
    ]
