# Generated by Django 4.1.5 on 2023-03-21 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0004_alter_person_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='Username',
        ),
        migrations.AddField(
            model_name='person',
            name='username',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
