# Generated by Django 3.2.9 on 2023-03-29 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0005_remove_person_username_person_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='Password',
            new_name='password',
        ),
    ]
