# Generated by Django 3.2.9 on 2023-05-24 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0008_feed'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feed',
        ),
    ]
