# Generated by Django 3.2.9 on 2023-07-09 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0009_delete_feed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='About',
        ),
    ]
