# Generated by Django 3.2.9 on 2023-05-24 17:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workshop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkshopSharing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=255)),
                ('Message', models.CharField(max_length=255)),
                ('Photo', models.ImageField(blank=True, default='', null=True, upload_to='uploads/')),
                ('Video', models.FileField(blank=True, default='', null=True, upload_to='uploads/')),
                ('Creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'WorkshopSharing',
            },
        ),
    ]
