# Generated by Django 3.2.9 on 2023-05-24 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0002_workshopsharing'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshopsharing',
            name='Workshop_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='workshop.workshop'),
            preserve_default=False,
        ),
    ]
