# Generated by Django 3.2.9 on 2023-05-27 04:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0003_workshopsharing_workshop_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop',
            name='RegistrationDue',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
