# Generated by Django 3.2.9 on 2023-06-06 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0004_workshop_registrationdue'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='Messages',
            field=models.CharField(default='', max_length=250, null=True),
        ),
    ]
