# Generated by Django 3.2.9 on 2023-06-19 18:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workshop', '0005_booking_messages'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Messages', models.CharField(default='', max_length=250, null=True)),
                ('Participant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('WorkshopFk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='workshop.workshop')),
            ],
            options={
                'db_table': 'inbox',
            },
        ),
    ]
