# Generated by Django 3.2.9 on 2023-06-20 03:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0008_inbox_workshoptitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='inbox',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
