# Generated by Django 3.2.9 on 2024-05-28 05:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20240521_2233'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.CharField(default=django.utils.timezone.now, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='shipping',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
