# Generated by Django 3.2.9 on 2023-06-19 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sharing', '0005_remove_likes_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grouptimelinecomment',
            name='GrpFeedFK',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groupcomments', to='sharing.grouptimeline'),
        ),
    ]
