# Generated by Django 3.2.9 on 2023-07-09 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0009_delete_feed'),
        ('sharing', '0006_alter_grouptimelinecomment_grpfeedfk'),
    ]

    operations = [
        migrations.CreateModel(
            name='GFeedSoilTagging',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FeedSoilTag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soilTagging', to='sharing.grouptimeline')),
                ('soilTag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.soiltag')),
            ],
            options={
                'unique_together': {('FeedSoilTag', 'soilTag')},
            },
        ),
        migrations.CreateModel(
            name='GFeedPlantTagging',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FeedPlantTag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plantTagging', to='sharing.grouptimeline')),
                ('plantTag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.planttag')),
            ],
            options={
                'unique_together': {('FeedPlantTag', 'plantTag')},
            },
        ),
    ]
