# Generated by Django 3.2.9 on 2023-07-09 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sharing', '0007_gfeedplanttagging_gfeedsoiltagging'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='Video',
        ),
        migrations.RemoveField(
            model_name='feed',
            name='Video',
        ),
        migrations.RemoveField(
            model_name='grouptimeline',
            name='GroupVideo',
        ),
        migrations.RemoveField(
            model_name='grouptimelinecomment',
            name='GrpVideo',
        ),
    ]
