# Generated by Django 3.2.9 on 2024-06-13 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0001_initial'),
    ]

    operations = [
    ]
