# Generated by Django 3.2.9 on 2024-06-13 06:21

from django.db import migrations
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0002_delete_basket'),
        ('basket', '0003_basket_prodreview'),
    ]

    operations = [
        migrations.CreateModel(
            name='prodReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(blank=True, max_length=1500)),
                ('restricted', models.BooleanField(default=False)),
                ('Person_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('basketid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basket.basket')),
                ('productid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplace.prodproduct')),
            ],
            options={
                'db_table': 'prodReview',
            },
        ),
    ]
