# Generated by Django 3.2.9 on 2024-06-13 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0004_merge_0002_delete_basket_0003_basket_prodreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='test_fix',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='prodreview',
            name='test_fix',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
