# Generated by Django 3.2.9 on 2024-06-13 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0005_auto_20240613_1425'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basket',
            name='test_fix',
        ),
        migrations.RemoveField(
            model_name='prodreview',
            name='test_fix',
        ),
    ]
