# Generated by Django 3.2.9 on 2024-06-13 07:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0006_auto_20240613_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='prodreview',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
